language: bash
env:
  matrix:
  - OS=debian DIST=jessie ARCH=armel
  - OS=debian DIST=jessie ARCH=armhf
  global:
  - secure: uB8WbkN+DidLR55voa/Z+9mrd9j2jXABvTh5BeznZbYcuHsJKpslD2rxzEXb57h+0axctMJBvABxtddWoR6oCuTz3rNg2wepFxR+OS4A5CZ3hgcQzT9zlvmEOCF+QAdfoJdB6yZae8Xwfvh0zOzvzR8n4sMwJ/wM/r5k707W0L3JmSN7ls+8mbgoNx/lfcpuY6Mvxm4CXak+vVug11r0VIgL9fKya51FB8OTyAGQpoQyZabgeaHZaiVRhoR89waa2GfnhvoUT+P7bcWBl9SjnTH32GMmU/I/3fpDi9Zb7mDW65AG0DuRF00JoJLVyiM7wUMz+Cc2kamsSDtZr6tqqSyK5s/o4Xto33Z3Uj1TE2UN9YSOcFl02YtIL78pfv8wIZB7bXtyt/0hdZXxqCeIYVvq2pqe0fI+Q6PaZBd33TvWHYRYRysetFjMJZ+eWVOGWnfHmaH9amQKbx/1sCu7g/w3NlN5aLwz5n2TRFO/LC3pXMNqt+ZWwMmWSJc/9l9XF+wEgEwtfThYQkE73nyntPnSd5KnsN3jbNbpz3muHb+aV3WdjJPu69eykSmH8GVZrB3pb8LfXGyPDkfwliAQP//WwbGm+XyiIu2lUYXSz5YVgjycQp8QyGdy+8MF8HpnswwB1atRYpEoQCwak6h7NQzOZn3TOK5GNluYsxkX5A0=
  - secure: ST/UvuG5Plds4aorMvBjQKvDGeyOPeoI9c6Vpn2Y3bVGzcJcviTE3vIY8BEWSz2uU+V2DLjN1d7by7QMYInNs1+EHWpZBnhEJgVPdVZJxy2sp5oQYlq13iBQiVje2BIHZlYuMirxrM4nyOoy9Dv+6mrWHde2iZjeqS+j/CplkTLJoiUxj+OWhDJmWGbUBU65QgbyKNubeQxKRB2f+AwE2ExRYXyPFkSmZuA94a4+2N5B8Xl0KhL3PIJflcERQWbHITy0lIHh0DLaCmBo0qKlSC2/ycxPJ03tRc7YhlGSjiWQt66k5Z2pYeCAekYdyzpGZPH/JCWFJH0aDnFpoAQN3FmN8xJdCIq14ovSKNVANUOK+IO5GLJyfwCEzEdSHeMB/1X6uUFrjLR/R8dSct0XwerfiD09sVDF3pvffBGNc2qv9V5azpqGp1TgoE2UefXiWuvy9mSJ6ttwKpZfK8vLNRLUzAe8/1Wfpv0Q+2PDrVKaJsX6nTJdhJe5dwSuzQzuqd3XUZs2BsI7G3A0OJ25yWS4d2c8UpOT1aYl+BjgCN1FDHolNgdBa0jYCdBQto+LOK8pDbGuchLf8B9guzyavl1aqJVKmLfbKl7kbac/FKrvDQ71OgbH8gcLvakRP1IlEyRdz4oDguC7J7gSUvZFK9NRm/jpfprmdFEZO+DVILs=
  - secure: KdnQcQotUi03yRBco4NvFCfrr/BwCteJmyRkjyfqjJpqKTKlRUYYiCaV5RVAYNCd9mfL0a/suMt7/tDnCkgPS1VsaDksXBD6LyjUH3job0h2bEVyzxbAe3EX+r+/XNMwb2IA0103prgSiRO4xf3orwuKzwGxufcyqG47DQNGclMhTeehru3GpExtFwb8ClWqkIPuMgScqdfaJyJiyZkhAy7vR+8mdnyyvQnql/FvusX+bysrEzs8KOy2TuwtKvzNrFx/uvWl9rPnrrRIIpzo/d7nJ903/iJNLshb3IJttej+CSGn5SKgxyLmQj/qUI4ppRLL1nnsoA0Vsh5RtpsRc4rzbmdpV0jnw8pYPzF3QI8Jz0aRUS6XoCO1Osse9sEsVILj1KNwia6VBo7ClppxQdaxsznv5X0Tn5oYwGCC/Eprjz1Mai4pw9NBppos8QSu9zXRPMaq6E9u9AAxVhp1PBKw2nanjjkeGWPG5DQKDlHUJiNG1nFP9Oc9hL9ZP7iuchK8d666JxBrD69I47rumC8PD8AZCHP9Kbn37AAjHEezcjOmLT7U/X7NG8yNfO4IRvvKJ2ZZ2vO/GMtRgEFwhHgzKdlQpvCOq/6JcNLqMK22sjcFdm8RhSNaGtgW3+Wdfiy8umuIgp0NFHQdJaoPUE7HPwqk6aNJzvCZmsqSJ7M=
sudo: required
dist: trusty
services: docker
install:
- sudo apt-get update
- sudo apt-get install --yes qemu-user-static
before_script:
- docker --version
script:
- docker build
  -t ev3dev/$OS-$DIST-$ARCH-cross
  -f ev3dev-$DIST/$OS-$DIST-$ARCH.dockerfile
  ev3dev-$DIST
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ];
  then
    export TAG=$(date --iso-8601);
    docker login -u $USER -p $PASSWORD -e $EMAIL;
    docker push ev3dev/$OS-$DIST-$ARCH-cross;
    docker tag $OS-$DIST-$ARCH-cross ev3dev/$OS-$DIST-$ARCH-cross:$TAG;
    docker push ev3dev/$OS-$DIST-$ARCH-cross:$TAG;
  fi
