language: bash
sudo: required
dist: trusty
services: docker
before_script:
- docker --version
script:
- docker build
  -t ev3dev/debian-jessie-cross
  -f ev3dev-jessie/debian-jessie-cross.dockerfile
  ev3dev-jessie
